// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createOrderStmt, err = db.PrepareContext(ctx, createOrder); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrder: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.debitUserBalanceStmt, err = db.PrepareContext(ctx, debitUserBalance); err != nil {
		return nil, fmt.Errorf("error preparing query DebitUserBalance: %w", err)
	}
	if q.getAllUsersStmt, err = db.PrepareContext(ctx, getAllUsers); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUsers: %w", err)
	}
	if q.getHighestPriceBuyerStmt, err = db.PrepareContext(ctx, getHighestPriceBuyer); err != nil {
		return nil, fmt.Errorf("error preparing query GetHighestPriceBuyer: %w", err)
	}
	if q.getMaxBuyStmt, err = db.PrepareContext(ctx, getMaxBuy); err != nil {
		return nil, fmt.Errorf("error preparing query GetMaxBuy: %w", err)
	}
	if q.getMaxBuyPriceOfaAssetStmt, err = db.PrepareContext(ctx, getMaxBuyPriceOfaAsset); err != nil {
		return nil, fmt.Errorf("error preparing query GetMaxBuyPriceOfaAsset: %w", err)
	}
	if q.getOpenBuyOrdersStmt, err = db.PrepareContext(ctx, getOpenBuyOrders); err != nil {
		return nil, fmt.Errorf("error preparing query GetOpenBuyOrders: %w", err)
	}
	if q.getOpenOrdersByAssetStmt, err = db.PrepareContext(ctx, getOpenOrdersByAsset); err != nil {
		return nil, fmt.Errorf("error preparing query GetOpenOrdersByAsset: %w", err)
	}
	if q.getOpenSellOrdersStmt, err = db.PrepareContext(ctx, getOpenSellOrders); err != nil {
		return nil, fmt.Errorf("error preparing query GetOpenSellOrders: %w", err)
	}
	if q.getOrdersByOrderIdStmt, err = db.PrepareContext(ctx, getOrdersByOrderId); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrdersByOrderId: %w", err)
	}
	if q.getPortfolioByUserIDStmt, err = db.PrepareContext(ctx, getPortfolioByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPortfolioByUserID: %w", err)
	}
	if q.getPortfolioByUserIdAndAssetStmt, err = db.PrepareContext(ctx, getPortfolioByUserIdAndAsset); err != nil {
		return nil, fmt.Errorf("error preparing query GetPortfolioByUserIdAndAsset: %w", err)
	}
	if q.getTradesByUserIDStmt, err = db.PrepareContext(ctx, getTradesByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTradesByUserID: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.insertPortfolioStmt, err = db.PrepareContext(ctx, insertPortfolio); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPortfolio: %w", err)
	}
	if q.insertTradeStmt, err = db.PrepareContext(ctx, insertTrade); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTrade: %w", err)
	}
	if q.updateOrderStatusStmt, err = db.PrepareContext(ctx, updateOrderStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOrderStatus: %w", err)
	}
	if q.updatePortfolioBalanceStmt, err = db.PrepareContext(ctx, updatePortfolioBalance); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePortfolioBalance: %w", err)
	}
	if q.updatePortfolioCreditQuantityStmt, err = db.PrepareContext(ctx, updatePortfolioCreditQuantity); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePortfolioCreditQuantity: %w", err)
	}
	if q.updatePortfolioDebitQuantityStmt, err = db.PrepareContext(ctx, updatePortfolioDebitQuantity); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePortfolioDebitQuantity: %w", err)
	}
	if q.updateUserBalanceDeltaStmt, err = db.PrepareContext(ctx, updateUserBalanceDelta); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserBalanceDelta: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createOrderStmt != nil {
		if cerr := q.createOrderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrderStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.debitUserBalanceStmt != nil {
		if cerr := q.debitUserBalanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing debitUserBalanceStmt: %w", cerr)
		}
	}
	if q.getAllUsersStmt != nil {
		if cerr := q.getAllUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUsersStmt: %w", cerr)
		}
	}
	if q.getHighestPriceBuyerStmt != nil {
		if cerr := q.getHighestPriceBuyerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHighestPriceBuyerStmt: %w", cerr)
		}
	}
	if q.getMaxBuyStmt != nil {
		if cerr := q.getMaxBuyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMaxBuyStmt: %w", cerr)
		}
	}
	if q.getMaxBuyPriceOfaAssetStmt != nil {
		if cerr := q.getMaxBuyPriceOfaAssetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMaxBuyPriceOfaAssetStmt: %w", cerr)
		}
	}
	if q.getOpenBuyOrdersStmt != nil {
		if cerr := q.getOpenBuyOrdersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOpenBuyOrdersStmt: %w", cerr)
		}
	}
	if q.getOpenOrdersByAssetStmt != nil {
		if cerr := q.getOpenOrdersByAssetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOpenOrdersByAssetStmt: %w", cerr)
		}
	}
	if q.getOpenSellOrdersStmt != nil {
		if cerr := q.getOpenSellOrdersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOpenSellOrdersStmt: %w", cerr)
		}
	}
	if q.getOrdersByOrderIdStmt != nil {
		if cerr := q.getOrdersByOrderIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrdersByOrderIdStmt: %w", cerr)
		}
	}
	if q.getPortfolioByUserIDStmt != nil {
		if cerr := q.getPortfolioByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPortfolioByUserIDStmt: %w", cerr)
		}
	}
	if q.getPortfolioByUserIdAndAssetStmt != nil {
		if cerr := q.getPortfolioByUserIdAndAssetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPortfolioByUserIdAndAssetStmt: %w", cerr)
		}
	}
	if q.getTradesByUserIDStmt != nil {
		if cerr := q.getTradesByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTradesByUserIDStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.insertPortfolioStmt != nil {
		if cerr := q.insertPortfolioStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPortfolioStmt: %w", cerr)
		}
	}
	if q.insertTradeStmt != nil {
		if cerr := q.insertTradeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTradeStmt: %w", cerr)
		}
	}
	if q.updateOrderStatusStmt != nil {
		if cerr := q.updateOrderStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOrderStatusStmt: %w", cerr)
		}
	}
	if q.updatePortfolioBalanceStmt != nil {
		if cerr := q.updatePortfolioBalanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePortfolioBalanceStmt: %w", cerr)
		}
	}
	if q.updatePortfolioCreditQuantityStmt != nil {
		if cerr := q.updatePortfolioCreditQuantityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePortfolioCreditQuantityStmt: %w", cerr)
		}
	}
	if q.updatePortfolioDebitQuantityStmt != nil {
		if cerr := q.updatePortfolioDebitQuantityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePortfolioDebitQuantityStmt: %w", cerr)
		}
	}
	if q.updateUserBalanceDeltaStmt != nil {
		if cerr := q.updateUserBalanceDeltaStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserBalanceDeltaStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                DBTX
	tx                                *sql.Tx
	createOrderStmt                   *sql.Stmt
	createUserStmt                    *sql.Stmt
	debitUserBalanceStmt              *sql.Stmt
	getAllUsersStmt                   *sql.Stmt
	getHighestPriceBuyerStmt          *sql.Stmt
	getMaxBuyStmt                     *sql.Stmt
	getMaxBuyPriceOfaAssetStmt        *sql.Stmt
	getOpenBuyOrdersStmt              *sql.Stmt
	getOpenOrdersByAssetStmt          *sql.Stmt
	getOpenSellOrdersStmt             *sql.Stmt
	getOrdersByOrderIdStmt            *sql.Stmt
	getPortfolioByUserIDStmt          *sql.Stmt
	getPortfolioByUserIdAndAssetStmt  *sql.Stmt
	getTradesByUserIDStmt             *sql.Stmt
	getUserByEmailStmt                *sql.Stmt
	getUserByIDStmt                   *sql.Stmt
	getUserByUsernameStmt             *sql.Stmt
	insertPortfolioStmt               *sql.Stmt
	insertTradeStmt                   *sql.Stmt
	updateOrderStatusStmt             *sql.Stmt
	updatePortfolioBalanceStmt        *sql.Stmt
	updatePortfolioCreditQuantityStmt *sql.Stmt
	updatePortfolioDebitQuantityStmt  *sql.Stmt
	updateUserBalanceDeltaStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                tx,
		tx:                                tx,
		createOrderStmt:                   q.createOrderStmt,
		createUserStmt:                    q.createUserStmt,
		debitUserBalanceStmt:              q.debitUserBalanceStmt,
		getAllUsersStmt:                   q.getAllUsersStmt,
		getHighestPriceBuyerStmt:          q.getHighestPriceBuyerStmt,
		getMaxBuyStmt:                     q.getMaxBuyStmt,
		getMaxBuyPriceOfaAssetStmt:        q.getMaxBuyPriceOfaAssetStmt,
		getOpenBuyOrdersStmt:              q.getOpenBuyOrdersStmt,
		getOpenOrdersByAssetStmt:          q.getOpenOrdersByAssetStmt,
		getOpenSellOrdersStmt:             q.getOpenSellOrdersStmt,
		getOrdersByOrderIdStmt:            q.getOrdersByOrderIdStmt,
		getPortfolioByUserIDStmt:          q.getPortfolioByUserIDStmt,
		getPortfolioByUserIdAndAssetStmt:  q.getPortfolioByUserIdAndAssetStmt,
		getTradesByUserIDStmt:             q.getTradesByUserIDStmt,
		getUserByEmailStmt:                q.getUserByEmailStmt,
		getUserByIDStmt:                   q.getUserByIDStmt,
		getUserByUsernameStmt:             q.getUserByUsernameStmt,
		insertPortfolioStmt:               q.insertPortfolioStmt,
		insertTradeStmt:                   q.insertTradeStmt,
		updateOrderStatusStmt:             q.updateOrderStatusStmt,
		updatePortfolioBalanceStmt:        q.updatePortfolioBalanceStmt,
		updatePortfolioCreditQuantityStmt: q.updatePortfolioCreditQuantityStmt,
		updatePortfolioDebitQuantityStmt:  q.updatePortfolioDebitQuantityStmt,
		updateUserBalanceDeltaStmt:        q.updateUserBalanceDeltaStmt,
	}
}
