// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type OrderStatus string

const (
	OrderStatusOPEN      OrderStatus = "OPEN"
	OrderStatusPARTIAL   OrderStatus = "PARTIAL"
	OrderStatusFILLED    OrderStatus = "FILLED"
	OrderStatusCANCELLED OrderStatus = "CANCELLED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type OrderType string

const (
	OrderTypeBUY  OrderType = "BUY"
	OrderTypeSELL OrderType = "SELL"
)

func (e *OrderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderType(s)
	case string:
		*e = OrderType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderType: %T", src)
	}
	return nil
}

type NullOrderType struct {
	OrderType OrderType `json:"order_type"`
	Valid     bool      `json:"valid"` // Valid is true if OrderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderType) Scan(value interface{}) error {
	if value == nil {
		ns.OrderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderType), nil
}

type Orders struct {
	ID                int64        `json:"id"`
	UserID            int64        `json:"user_id"`
	Asset             string       `json:"asset"`
	Type              OrderType    `json:"type"`
	Price             int64        `json:"price"`
	Quantity          int64        `json:"quantity"`
	RemainingQuantity int64        `json:"remaining_quantity"`
	Status            OrderStatus  `json:"status"`
	CreatedAt         sql.NullTime `json:"created_at"`
}

type Portfolio struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Asset     string       `json:"asset"`
	Quantity  int64        `json:"quantity"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Trades struct {
	ID          int64        `json:"id"`
	BuyOrderID  int64        `json:"buy_order_id"`
	SellOrderID int64        `json:"sell_order_id"`
	Asset       string       `json:"asset"`
	Price       int64        `json:"price"`
	Quantity    int64        `json:"quantity"`
	ExecutedAt  sql.NullTime `json:"executed_at"`
}

type Users struct {
	ID           int64        `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	Balance      int64        `json:"balance"`
	CreatedAt    sql.NullTime `json:"created_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}
