// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
	"database/sql"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id,
    asset,
    type,
    price,
    quantity,
    remaining_quantity
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, asset, type, price, quantity, remaining_quantity, status, created_at
`

type CreateOrderParams struct {
	UserID            int64     `json:"user_id"`
	Asset             string    `json:"asset"`
	Type              OrderType `json:"type"`
	Price             int64     `json:"price"`
	Quantity          int64     `json:"quantity"`
	RemainingQuantity int64     `json:"remaining_quantity"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Orders, error) {
	row := q.queryRow(ctx, q.createOrderStmt, createOrder,
		arg.UserID,
		arg.Asset,
		arg.Type,
		arg.Price,
		arg.Quantity,
		arg.RemainingQuantity,
	)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Type,
		&i.Price,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getHighestPriceBuyer = `-- name: GetHighestPriceBuyer :many
SELECT id, user_id, asset, type, price, quantity, remaining_quantity, status, created_at
FROM orders
WHERE type = 'BUY'
  AND status = 'OPEN'
  AND asset = $1
  AND price >= $2
ORDER BY price DESC
`

type GetHighestPriceBuyerParams struct {
	Asset string `json:"asset"`
	Price int64  `json:"price"`
}

func (q *Queries) GetHighestPriceBuyer(ctx context.Context, arg GetHighestPriceBuyerParams) ([]Orders, error) {
	rows, err := q.query(ctx, q.getHighestPriceBuyerStmt, getHighestPriceBuyer, arg.Asset, arg.Price)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Orders{}
	for rows.Next() {
		var i Orders
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Asset,
			&i.Type,
			&i.Price,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxBuy = `-- name: GetMaxBuy :many
SELECT asset, MAX(price) AS max_buy_price
FROM orders
WHERE type = 'BUY'
  AND status IN ('OPEN', 'PARTIAL')
GROUP BY asset
`

type GetMaxBuyRow struct {
	Asset       string      `json:"asset"`
	MaxBuyPrice interface{} `json:"max_buy_price"`
}

func (q *Queries) GetMaxBuy(ctx context.Context) ([]GetMaxBuyRow, error) {
	rows, err := q.query(ctx, q.getMaxBuyStmt, getMaxBuy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMaxBuyRow{}
	for rows.Next() {
		var i GetMaxBuyRow
		if err := rows.Scan(&i.Asset, &i.MaxBuyPrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxBuyPriceOfaAsset = `-- name: GetMaxBuyPriceOfaAsset :one
SELECT id,
       asset,
       user_id,
       price AS max_buy_price,
       quantity,
       remaining_quantity,
       status,
       created_at
FROM orders
WHERE type = 'BUY'
  AND status IN ('OPEN', 'PARTIAL')
  AND asset = $1
ORDER BY price DESC
LIMIT 1
`

type GetMaxBuyPriceOfaAssetRow struct {
	ID                int64        `json:"id"`
	Asset             string       `json:"asset"`
	UserID            int64        `json:"user_id"`
	MaxBuyPrice       int64        `json:"max_buy_price"`
	Quantity          int64        `json:"quantity"`
	RemainingQuantity int64        `json:"remaining_quantity"`
	Status            OrderStatus  `json:"status"`
	CreatedAt         sql.NullTime `json:"created_at"`
}

func (q *Queries) GetMaxBuyPriceOfaAsset(ctx context.Context, asset string) (GetMaxBuyPriceOfaAssetRow, error) {
	row := q.queryRow(ctx, q.getMaxBuyPriceOfaAssetStmt, getMaxBuyPriceOfaAsset, asset)
	var i GetMaxBuyPriceOfaAssetRow
	err := row.Scan(
		&i.ID,
		&i.Asset,
		&i.UserID,
		&i.MaxBuyPrice,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenBuyOrders = `-- name: GetOpenBuyOrders :many
SELECT id, user_id, asset, type, price, quantity, remaining_quantity, status, created_at FROM orders
WHERE type = 'BUY' 
  AND remaining_quantity > 0
ORDER BY price DESC, created_at ASC
`

func (q *Queries) GetOpenBuyOrders(ctx context.Context) ([]Orders, error) {
	rows, err := q.query(ctx, q.getOpenBuyOrdersStmt, getOpenBuyOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Orders{}
	for rows.Next() {
		var i Orders
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Asset,
			&i.Type,
			&i.Price,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenOrdersByAsset = `-- name: GetOpenOrdersByAsset :many
SELECT id, user_id, asset, type, price, quantity, remaining_quantity, status, created_at
FROM orders
WHERE asset = $1
  AND status = 'OPEN'
ORDER BY type DESC, price DESC, created_at ASC
`

func (q *Queries) GetOpenOrdersByAsset(ctx context.Context, asset string) ([]Orders, error) {
	rows, err := q.query(ctx, q.getOpenOrdersByAssetStmt, getOpenOrdersByAsset, asset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Orders{}
	for rows.Next() {
		var i Orders
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Asset,
			&i.Type,
			&i.Price,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenSellOrders = `-- name: GetOpenSellOrders :many
SELECT id, user_id, asset, type, price, quantity, remaining_quantity, status, created_at FROM orders
WHERE type = 'SELL' 
  AND remaining_quantity > 0
ORDER BY price ASC, created_at ASC
`

func (q *Queries) GetOpenSellOrders(ctx context.Context) ([]Orders, error) {
	rows, err := q.query(ctx, q.getOpenSellOrdersStmt, getOpenSellOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Orders{}
	for rows.Next() {
		var i Orders
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Asset,
			&i.Type,
			&i.Price,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByOrderId = `-- name: GetOrdersByOrderId :one
SELECT id, user_id, asset, type, price, quantity, remaining_quantity, status, created_at
FROM orders
WHERE id = $1
  AND status = 'OPEN'
`

func (q *Queries) GetOrdersByOrderId(ctx context.Context, id int64) (Orders, error) {
	row := q.queryRow(ctx, q.getOrdersByOrderIdStmt, getOrdersByOrderId, id)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Type,
		&i.Price,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET remaining_quantity = $1,
    status = $2
WHERE id = $3
RETURNING id, user_id, asset, type, price, quantity, remaining_quantity, status, created_at
`

type UpdateOrderStatusParams struct {
	RemainingQuantity int64       `json:"remaining_quantity"`
	Status            OrderStatus `json:"status"`
	ID                int64       `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Orders, error) {
	row := q.queryRow(ctx, q.updateOrderStatusStmt, updateOrderStatus, arg.RemainingQuantity, arg.Status, arg.ID)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Type,
		&i.Price,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
