// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portfolio.sql

package db

import (
	"context"
)

const getPortfolioByUserID = `-- name: GetPortfolioByUserID :many
SELECT id, user_id, asset, quantity, updated_at
FROM portfolio
WHERE user_id = $1
`

func (q *Queries) GetPortfolioByUserID(ctx context.Context, userID int64) ([]Portfolio, error) {
	rows, err := q.query(ctx, q.getPortfolioByUserIDStmt, getPortfolioByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Portfolio{}
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Asset,
			&i.Quantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPortfolioByUserIdAndAsset = `-- name: GetPortfolioByUserIdAndAsset :one
SELECT id, user_id, asset, quantity, updated_at
FROM portfolio
WHERE user_id = $1 AND asset=$2
`

type GetPortfolioByUserIdAndAssetParams struct {
	UserID int64  `json:"user_id"`
	Asset  string `json:"asset"`
}

func (q *Queries) GetPortfolioByUserIdAndAsset(ctx context.Context, arg GetPortfolioByUserIdAndAssetParams) (Portfolio, error) {
	row := q.queryRow(ctx, q.getPortfolioByUserIdAndAssetStmt, getPortfolioByUserIdAndAsset, arg.UserID, arg.Asset)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Quantity,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPortfolio = `-- name: InsertPortfolio :one
INSERT INTO portfolio (user_id, asset, quantity)
VALUES ($1, $2, $3)
RETURNING id, user_id, asset, quantity, updated_at
`

type InsertPortfolioParams struct {
	UserID   int64  `json:"user_id"`
	Asset    string `json:"asset"`
	Quantity int64  `json:"quantity"`
}

func (q *Queries) InsertPortfolio(ctx context.Context, arg InsertPortfolioParams) (Portfolio, error) {
	row := q.queryRow(ctx, q.insertPortfolioStmt, insertPortfolio, arg.UserID, arg.Asset, arg.Quantity)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Quantity,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePortfolioBalance = `-- name: UpdatePortfolioBalance :one
UPDATE portfolio
SET quantity = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $2
  AND asset = $3
RETURNING id, user_id, asset, quantity, updated_at
`

type UpdatePortfolioBalanceParams struct {
	Quantity int64  `json:"quantity"`
	UserID   int64  `json:"user_id"`
	Asset    string `json:"asset"`
}

func (q *Queries) UpdatePortfolioBalance(ctx context.Context, arg UpdatePortfolioBalanceParams) (Portfolio, error) {
	row := q.queryRow(ctx, q.updatePortfolioBalanceStmt, updatePortfolioBalance, arg.Quantity, arg.UserID, arg.Asset)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Quantity,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePortfolioCreditQuantity = `-- name: UpdatePortfolioCreditQuantity :one
UPDATE portfolio
SET quantity = quantity+$1,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $2
  AND asset = $3
RETURNING id, user_id, asset, quantity, updated_at
`

type UpdatePortfolioCreditQuantityParams struct {
	Quantity int64  `json:"quantity"`
	UserID   int64  `json:"user_id"`
	Asset    string `json:"asset"`
}

func (q *Queries) UpdatePortfolioCreditQuantity(ctx context.Context, arg UpdatePortfolioCreditQuantityParams) (Portfolio, error) {
	row := q.queryRow(ctx, q.updatePortfolioCreditQuantityStmt, updatePortfolioCreditQuantity, arg.Quantity, arg.UserID, arg.Asset)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Quantity,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePortfolioDebitQuantity = `-- name: UpdatePortfolioDebitQuantity :one
UPDATE portfolio
SET quantity = quantity-$1,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $2
  AND asset = $3
RETURNING id, user_id, asset, quantity, updated_at
`

type UpdatePortfolioDebitQuantityParams struct {
	Quantity int64  `json:"quantity"`
	UserID   int64  `json:"user_id"`
	Asset    string `json:"asset"`
}

func (q *Queries) UpdatePortfolioDebitQuantity(ctx context.Context, arg UpdatePortfolioDebitQuantityParams) (Portfolio, error) {
	row := q.queryRow(ctx, q.updatePortfolioDebitQuantityStmt, updatePortfolioDebitQuantity, arg.Quantity, arg.UserID, arg.Asset)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Quantity,
		&i.UpdatedAt,
	)
	return i, err
}
