// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Orders, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DebitUserBalance(ctx context.Context, arg DebitUserBalanceParams) (Users, error)
	GetAllUsers(ctx context.Context) ([]Users, error)
	GetHighestPriceBuyer(ctx context.Context, arg GetHighestPriceBuyerParams) ([]Orders, error)
	GetMaxBuy(ctx context.Context) ([]GetMaxBuyRow, error)
	GetMaxBuyPriceOfaAsset(ctx context.Context, asset string) (GetMaxBuyPriceOfaAssetRow, error)
	GetOpenBuyOrders(ctx context.Context) ([]Orders, error)
	GetOpenOrdersByAsset(ctx context.Context, asset string) ([]Orders, error)
	GetOpenSellOrders(ctx context.Context) ([]Orders, error)
	GetOrdersByOrderId(ctx context.Context, id int64) (Orders, error)
	GetPortfolioByUserID(ctx context.Context, userID int64) (Portfolio, error)
	GetPortfolioByUserIdAndAsset(ctx context.Context, arg GetPortfolioByUserIdAndAssetParams) (Portfolio, error)
	GetTradesByUserID(ctx context.Context, userID int64) ([]Trades, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id int64) (Users, error)
	GetUserByUsername(ctx context.Context, username string) (Users, error)
	InsertPortfolio(ctx context.Context, arg InsertPortfolioParams) (Portfolio, error)
	InsertTrade(ctx context.Context, arg InsertTradeParams) (Trades, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Orders, error)
	UpdatePortfolioBalance(ctx context.Context, arg UpdatePortfolioBalanceParams) (Portfolio, error)
	UpdatePortfolioCreditQuantity(ctx context.Context, arg UpdatePortfolioCreditQuantityParams) (Portfolio, error)
	UpdatePortfolioDebitQuantity(ctx context.Context, arg UpdatePortfolioDebitQuantityParams) (Portfolio, error)
	UpdateUserBalanceDelta(ctx context.Context, arg UpdateUserBalanceDeltaParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
