// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trades.sql

package db

import (
	"context"
)

const getTradesByUserID = `-- name: GetTradesByUserID :many
SELECT t.id, t.buy_order_id, t.sell_order_id, t.asset, t.price, t.quantity, t.executed_at
FROM trades t
JOIN orders o
  ON t.buy_order_id = o.id
  OR t.sell_order_id = o.id
WHERE o.user_id = $1
`

func (q *Queries) GetTradesByUserID(ctx context.Context, userID int64) ([]Trades, error) {
	rows, err := q.query(ctx, q.getTradesByUserIDStmt, getTradesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trades{}
	for rows.Next() {
		var i Trades
		if err := rows.Scan(
			&i.ID,
			&i.BuyOrderID,
			&i.SellOrderID,
			&i.Asset,
			&i.Price,
			&i.Quantity,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTrade = `-- name: InsertTrade :one
INSERT INTO trades (
    buy_order_id,
    sell_order_id,
    asset,
    price,
    quantity
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, buy_order_id, sell_order_id, asset, price, quantity, executed_at
`

type InsertTradeParams struct {
	BuyOrderID  int64  `json:"buy_order_id"`
	SellOrderID int64  `json:"sell_order_id"`
	Asset       string `json:"asset"`
	Price       int64  `json:"price"`
	Quantity    int64  `json:"quantity"`
}

func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) (Trades, error) {
	row := q.queryRow(ctx, q.insertTradeStmt, insertTrade,
		arg.BuyOrderID,
		arg.SellOrderID,
		arg.Asset,
		arg.Price,
		arg.Quantity,
	)
	var i Trades
	err := row.Scan(
		&i.ID,
		&i.BuyOrderID,
		&i.SellOrderID,
		&i.Asset,
		&i.Price,
		&i.Quantity,
		&i.ExecutedAt,
	)
	return i, err
}
