// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    password_hash,
    balance
)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, password_hash, balance, created_at, deleted_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Balance      int64  `json:"balance"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Balance,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Balance,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const debitUserBalance = `-- name: DebitUserBalance :one
UPDATE users
SET balance = balance - $1
WHERE id = $2
  AND balance >= $1
RETURNING id, username, email, password_hash, balance, created_at, deleted_at
`

type DebitUserBalanceParams struct {
	Balance int64 `json:"balance"`
	ID      int64 `json:"id"`
}

func (q *Queries) DebitUserBalance(ctx context.Context, arg DebitUserBalanceParams) (Users, error) {
	row := q.queryRow(ctx, q.debitUserBalanceStmt, debitUserBalance, arg.Balance, arg.ID)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Balance,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, email, password_hash, balance, created_at, deleted_at
FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]Users, error) {
	rows, err := q.query(ctx, q.getAllUsersStmt, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Balance,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, balance, created_at, deleted_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Users, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Balance,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, balance, created_at, deleted_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (Users, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Balance,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, balance, created_at, deleted_at
FROM users
WHERE username = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (Users, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Balance,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserBalanceDelta = `-- name: UpdateUserBalanceDelta :one
UPDATE users
SET balance = balance + $1
WHERE id = $2
RETURNING id, username, email, password_hash, balance, created_at, deleted_at
`

type UpdateUserBalanceDeltaParams struct {
	Balance int64 `json:"balance"`
	ID      int64 `json:"id"`
}

func (q *Queries) UpdateUserBalanceDelta(ctx context.Context, arg UpdateUserBalanceDeltaParams) (Users, error) {
	row := q.queryRow(ctx, q.updateUserBalanceDeltaStmt, updateUserBalanceDelta, arg.Balance, arg.ID)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Balance,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
